name: tinnitustamer
title: Tinnitus Tamer
#adopt-info: tinnitustamer
version: '1.0'
summary: An application to help with tinnitustamer
description: |
  Tinnitus Tamer is a Python application designed to provide relief for tinnitus sufferers by generating and mixing calming sounds, including white, pink, brown, wind, ocean, and waterfall noises. It features a customizable notch filter to target specific tinnitus frequencies and system tray integration for background playback.

grade: stable
confinement: strict
license: MIT
base: core24
compression: lzo

contact: https://github.com/kz6fittycent/tinnitus_tamer/issues
issues: https://github.com/kz6fittycent/tinnitus_tamer/issues
source-code: https://github.com/kz6fittycent/tinnitus_tamer
icon: snap/gui/tinnitus_tamer.png
donation: https://www.patreon.com/kz6fittycent

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  tinnitustamer:
    extensions:
      - kde-neon-6
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/lib/python3.12/site-packages
      LD_LIBRARY_PATH: $SNAP/lib/python3.12/site-packages/PyQt6/Qt6:$SNAP/kf6/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:$SNAP/usr/lib:$SNAP/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lib/python3.12/site-packages/PyQt6/Qt6/plugins/platforms      
    command: usr/share/tinnitustamer/tinnitus_tamer.py 
    plugs:
      - audio-playback
      - home
      - desktop
    
parts:
  tinnitustamer:
    source: https://github.com/kz6fittycent/tinnitus_tamer
    source-type: git
    plugin: python
    python-requirements:
      - requirements.txt
    
    python-packages: 
      - PyQt6==6.5.0
            
    build-packages:
      - libxcb-cursor-dev
      - qt6-base-dev 
     
    stage-packages:
      - libasound2
      - libpulse0 
      - libxcb-cursor-dev  
      - xcb  
    
#    override-pull: |
#      craftctl default
#      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 
      
    override-build: |
      craftctl default
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/tinnitustamer/icons
      cp tinnitus_tamer.py $SNAPCRAFT_PART_INSTALL/usr/share/tinnitustamer/
      cp snap/gui/*.png $SNAPCRAFT_PART_INSTALL/usr/share/tinnitustamer/icons
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      cp snap/gui/tinnitus_tamer.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      
    organize:
      'usr/share/tinnitustamer/tinnitus_tamer.py': usr/share/tinnitustamer/tinnitus_tamer.py
      'usr/share/tinnitustamer/icons/*': usr/share/tinnitustamer/icons/               
